// <auto-generated />
namespace RnD.Net.EntityFramework.CD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class version_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201611262006310_version_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
