// <auto-generated />
namespace RnD.Net.EntityFramework.CD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class version_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201611281620348_version_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
